
import Project.ConnectionProvider;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author suman
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jFrame3 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SIGNUP background.PNG"))); // NOI18N

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(690, 290));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("First Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, -1));

        jLabel2.setText("Last Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, -1));

        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 90, -1));

        jLabel4.setText("Date Of Brith");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 90, -1));

        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 90, -1));

        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 90, -1));

        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 90, -1));

        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 90, -1));

        jLabel9.setText("Date Of Join");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 90, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 200, -1));
        jComboBox1.getAccessibleContext().setAccessibleName("gender");

        jTextPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(153, 153, 153));
        jTextPane1.setText("Enter First Name");
        jTextPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextPane1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPane1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 200, -1));

        jTextPane2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(153, 153, 153));
        jTextPane2.setText("Enter Last Name");
        jTextPane2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextPane2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPane2FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 200, -1));

        jTextPane3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextPane3.setForeground(new java.awt.Color(153, 153, 153));
        jTextPane3.setText("Enter Phone Number");
        jTextPane3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextPane3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPane3FocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(jTextPane3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 200, -1));

        jTextPane4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextPane4.setForeground(new java.awt.Color(153, 153, 153));
        jTextPane4.setText("Enter Date Of Brith");
        jTextPane4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextPane4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPane4FocusLost(evt);
            }
        });
        jScrollPane4.setViewportView(jTextPane4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 200, -1));

        jEditorPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jEditorPane1.setForeground(new java.awt.Color(153, 153, 153));
        jEditorPane1.setText("Enter Address");
        jEditorPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jEditorPane1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jEditorPane1FocusLost(evt);
            }
        });
        jScrollPane5.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 200, 40));

        jTextPane5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextPane5.setForeground(new java.awt.Color(153, 153, 153));
        jTextPane5.setText("Enter Email");
        jTextPane5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextPane5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPane5FocusLost(evt);
            }
        });
        jScrollPane6.setViewportView(jTextPane5);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 200, -1));

        jTextPane7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextPane7.setForeground(new java.awt.Color(153, 153, 153));
        jTextPane7.setText("Enter Date Of Join");
        jTextPane7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextPane7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPane7FocusLost(evt);
            }
        });
        jScrollPane8.setViewportView(jTextPane7);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 200, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("REGISTER ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        jButton1.setActionCommand("Register");
        jButton1.setLabel("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        jButton2.setLabel("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("Enter Password");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 180, -1));

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, 22));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SIGNUP background.PNG"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Fname = jTextPane1.getText();
        String Lname = jTextPane2.getText();
        String contactNo =jTextPane3.getText();
        String DOB = jTextPane4.getText();
        String gender = jComboBox1.getName();
        String address = jEditorPane1.getText();
        String email = jTextPane5.getText();
        String password = jPasswordField1.getText();
        String DOJ = jTextPane7.getText();
        
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rsid = st.executeQuery("select max(staff_id)from staff_details");
            rsid.next();
            int S_id = rsid.getInt(1);
            S_id = S_id + 1;
            ResultSet unid = st.executeQuery("select email, phone_no from staff_details");
            boolean insertData = true;
            while(unid.next()){
                if(jTextPane5.getText().equals(unid.getString(1))){
                    insertData = false;
                    JOptionPane.showMessageDialog(null, "The user email already exist \nPlease login usring user regiseter details");
                }
                if(jTextPane3.getText().equals(unid.getString(2))){
                  insertData = false;
                    JOptionPane.showMessageDialog(null, "The user number already exist \nPlease login usring user regiseter details");
                  
                }
            }
            if(insertData){
                st.execute("insert into staff_details value('"+S_id+"','"+Fname+"','"+Lname+"','"+contactNo+"','"+DOB+"','"+gender+"','"+address+"','"+email+"','"+password+"','"+DOJ+"')");
                JOptionPane.showMessageDialog(null, "Staf Added Successfully");
                setVisible(false);
                new login().setVisible(true);
            }
            
        }
            
           
        catch(Exception e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane1FocusGained
        // TODO add your handling code here:
        if(jTextPane1.getText().equals("Enter First Name")){
            jTextPane1.setText("");
            jTextPane1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTextPane1FocusGained

    private void jTextPane1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane1FocusLost
        // TODO add your handling code here:
        if(jTextPane1.getText().equals("")){
            jTextPane1.setText("Enter First Name");
            jTextPane1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextPane1FocusLost

    private void jTextPane2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane2FocusGained
        // TODO add your handling code here:
         if(jTextPane2.getText().equals("Enter Last Name")){
            jTextPane2.setText("");
            jTextPane2.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTextPane2FocusGained

    private void jTextPane2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane2FocusLost
        // TODO add your handling code here:
        if(jTextPane2.getText().equals("")){
            jTextPane2.setText("Enter Last Name");
            jTextPane2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextPane2FocusLost

    private void jTextPane3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane3FocusGained
        // TODO add your handling code here:
        if(jTextPane3.getText().equals("Enter Phone Number")){
            jTextPane3.setText("");
            jTextPane3.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTextPane3FocusGained

    private void jTextPane3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane3FocusLost
        // TODO add your handling code here:
        if(jTextPane3.getText().equals("")){
            jTextPane3.setText("Enter Phone Number");
            jTextPane3.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextPane3FocusLost

    private void jTextPane4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane4FocusGained
        // TODO add your handling code here:
        if(jTextPane4.getText().equals("Enter Date Of Brith")){
            jTextPane4.setText("");
            jTextPane4.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTextPane4FocusGained

    private void jTextPane4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane4FocusLost
        // TODO add your handling code here:
        if(jTextPane4.getText().equals("")){
            jTextPane4.setText("Enter Date Of Brith");
            jTextPane4.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextPane4FocusLost

    private void jEditorPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jEditorPane1FocusGained
        // TODO add your handling code here:
        if(jEditorPane1.getText().equals("Enter Address")){
            jEditorPane1.setText("");
            jEditorPane1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jEditorPane1FocusGained

    private void jEditorPane1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jEditorPane1FocusLost
        // TODO add your handling code here:
        if(jEditorPane1.getText().equals("")){
            jEditorPane1.setText("Enter Address");
            jEditorPane1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jEditorPane1FocusLost

    private void jTextPane5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane5FocusGained
        // TODO add your handling code here:
        if(jTextPane5.getText().equals("Enter Email")){
            jTextPane5.setText("");
            jTextPane5.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTextPane5FocusGained

    private void jTextPane5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane5FocusLost
        // TODO add your handling code here:
        if(jTextPane5.getText().equals("")){
            jTextPane5.setText("Enter Email");
            jTextPane5.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextPane5FocusLost

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        if(jPasswordField1.getText().equals("Enter Password")){
            jPasswordField1.setText("");
            jPasswordField1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
        if(jPasswordField1.getText().equals("")){
            jPasswordField1.setText("Enter Password");
            jPasswordField1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jTextPane7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane7FocusGained
        // TODO add your handling code here:
        if(jTextPane7.getText().equals("Enter Date Of Join")){
            jTextPane7.setText("");
            jTextPane7.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTextPane7FocusGained

    private void jTextPane7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane7FocusLost
        // TODO add your handling code here:
         if(jTextPane7.getText().equals("")){
            jTextPane7.setText("Enter Date Of Join");
            jTextPane7.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextPane7FocusLost

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            jPasswordField1.setEchoChar((char) 0);
        }
        else{
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane7;
    // End of variables declaration//GEN-END:variables
}
